### ISSUE TITLE
UI component - Textarea

### ISSUE THREAD

**Issue by d8660091** [icgc-argo/argo-platform#106]

**Comment by d8660091** [comment]
#104

**Comment by kcullion** [comment]
@d8660091 just one small thing. 
Can you remove the "type something" placeholder text from within the text area. I don't think we need to include that. thanks!
![Screen Shot 2019-06-18 at 10 44 02 AM](https://user-images.githubusercontent.com/18424138/59694058-02e2bc80-91b6-11e9-99be-cc87e2bba98c.png)
