### ISSUE TITLE
UI Component Library: Multi/Single-select input - Add New Value

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#109]
**Multi-select with add new**
Certain fields may allow the user to add multiple tags with some suggestions from a controlled list, but they can also add new values if their value isn't within the suggestions. 

- [x] default field looks like the usual multi-select input (with all of the input state styles applied)
- [x] The dropdown DOES NOT appear with suggestions until the user starts typing characters
- [x] If user doesn't see their value within the suggestions they can finish typing and select the bottom option "Their typed value (NEW VALUE)". This will add their new value as a tag (and also add it to the controlled list for future suggestions upon save).
- [x] The list of suggestions will get a scrollbar after 7 suggested values
- [x] Yellow highlight for the matching portions of the values

![Screen Shot 2019-06-13 at 3 58 30 PM](https://user-images.githubusercontent.com/18424138/59463600-6191ea00-8df4-11e9-96e7-4dc0a6cc0ae1.png)

Zeplin: https://zpl.io/adzPEOR
See in use: https://zpl.io/VkXGNDv

**Single-select with add new**
The user may also only be able to choose/add one value (like on the registration form):

- [x] All of the above requirements apply here except the one value is not displayed as a tag, it's displayed as an input value

![Screen Shot 2019-06-13 at 3 58 34 PM](https://user-images.githubusercontent.com/18424138/59463620-70789c80-8df4-11e9-8eaf-2ca2b274b5fb.png)

Zeplin: https://zpl.io/adzPEOR
See in use: https://zpl.io/VDKBrWW

Related issue: https://github.com/icgc-argo/argo-platform/issues/58

**Comment by kcullion** [comment]
@d8660091 There's a second part to this ticket - the Single-select with add new
has that been built in as an option for this component?

**Comment by d8660091** [comment]
single-select has not been addressed yet

**Comment by kcullion** [comment]
Ok thanks @d8660091 I'll move it back into "in progress".

Please also fix:
- [ ] For the text (New Value) - use the same style and capitalization as the "SUGGESTIONS" label:
![Screen Shot 2019-06-17 at 1 47 08 PM](https://user-images.githubusercontent.com/18424138/59625090-6dd4ba80-9106-11e9-8a46-511953e4ae23.png)

**Comment by kcullion** [comment]
@d8660091 all of this looks great! I have put some relevant feedback on this ticket: https://github.com/icgc-argo/argo-platform/issues/58
I will close this ticket now and we can just use that other ticket to keep track of the feedback for this one component.
