### ISSUE TITLE
Create Program: Change Layout of form 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#115]
- [x] Implement the single column layout 
- [x] Implement the membership type as a select `dropdown` 
- [ ] The CANCEL button will clear the form and take the user back to the All Programs list

Zeplin: https://zpl.io/agQ1Y9N

<img width="494" alt="Screen Shot 2019-06-20 at 10 45 14 AM" src="https://user-images.githubusercontent.com/18424138/59858212-86ccae00-9348-11e9-9496-22905787f253.png">

**Comment by hlminh2000** [comment]
curious on the Single column layout, did we consider making it single column in response to smaller screens rather than always? :)

**Comment by rosibaj** [comment]
@hlminh2000 No, it was more of a UX choice that Bashar and Kim discussed.  Single column layout was the favoured choice overall as it makes the form more clear overall?

**Comment by kcullion** [comment]
@hlminh2000 UX studies show that a form that is in one column is much easier to fill out than a form that required the user to understand which order the form fields are in when it's more than one column
https://baymard.com/blog/avoid-multi-column-forms

**Comment by ciaranschutte** [comment]
@rosibaj Can we move the 'Cancel' button functionality to a ticket with the 'Create' functionality?
Leave this ticket covering static UI.

**Comment by rosibaj** [comment]
@ciaranschutte I am fine with that

**Comment by rosibaj** [comment]
@ciaranschutte i am fine with that - https://github.com/icgc-argo/argo-platform/issues/205 created

**Comment by ciaranschutte** [comment]
@rosibaj @alekspejovic  https://platform-ui.qa.argo.cancercollaboratory.org/create-program

**Comment by alekspejovic** [comment]
Thanks Ciaran!

Some comments from me:
- [ ] From Kim's mockup, it looks like there should be more padding surrounding the form on both sides. Same thing goes for the padding within the form.
![image](https://user-images.githubusercontent.com/12387683/60605158-fd28d180-9d86-11e9-9cfd-8cfa97abe188.png)

- [ ] When you type something into a cell and  click enter, it doesn't  jump to the next cell 
- [ ] The dropdown for Country is hidden under the cell bellow it 
- [ ] When you select an option on the MembershipType, it doesn't display your selection
- [ ] When you erase all text in a field, the default text should return, and it doesn't
- [ ] Primary site & Institutions should also be a multi-select input (don't know whether this needs to be added as a new feature, @rosibaj , please confirm)
- [ ] The Processing Regions checkboxes are missing (also same question as above @rosibaj )

**Comment by rosibaj** [comment]
- Primary site & Institutions should also be a multi-select input 
- Processing regions should be added!

**Comment by ciaranschutte** [comment]
@alekspejovic @hlminh2000 @rosibaj 

-  "When you type something into a cell and click enter, it doesn't jump to the next cell"
requires further investigation, not default browser behaviour.
enter should submit form by default so we'll need some state to figure out which input should be focused.

- " When you select an option on the MembershipType, it doesn't display your selection"
This will be fixed when we hook up form state.

**Comment by rosibaj** [comment]
thanks @ciaranschutte - will make a ticket for the first item there!

**Comment by ciaranschutte** [comment]
most inputs will not work correctly because the data hookup is not done yet.
Eg. multiselects like Primary Site are MultiSelect components, but if you click on a selection to change it, it will break because we don't have an overall form state yet.

**Comment by ciaranschutte** [comment]
@rosibaj "When you erase text in field, default text should return"
I can't replicate. 

![inputtext.gif](https://images.zenhubusercontent.com/5b58924328d06e60f1c19ac1/a77a401f-adbe-4751-8a3b-901612eb4151)

**Comment by rosibaj** [comment]
@ciaranschutte  Apologies this is mistake on my part - what i really meant is that Primary site *should* have default text in it.  It looks correct in your video (but not on my screen).  What you have there looks good! we can consider that one resolved if your video is what is going to be merged!

**Comment by alekspejovic** [comment]
@ciaranschutte Hey just a couple of additional comments (I don't know whether these issues will be solved with the data hookup cause it looked like it was working in Jon's demo yesterday).

- [ ] For primary site & institution , you are able to see the dropdown list , but the blue tag doesn't show up when you select any of the options 
- [ ] For the Processing Regions,  nothing happens when you click the checkbox

https://drive.google.com/file/d/1lt-KrD3XzkqpzU2nNctH4eOQY-rsf1L_/view
