### ISSUE TITLE
Program Page - Profile Data Hookup

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#125]
Show all the correct data for a program when that program is loaded into the page

**Comment by alekspejovic** [comment]
Please make the following corrections : 

- [ ] Add users button should disappear when you are on the Profile Tab (should only be active on Users tab)
- [ ] Commitment level should be formatted as xxx,xxx Donors
- [ ] There is too much padding between the field names and the field values. There should also be more padding on the right side of the description (does not go all the way until the end of the form)
- [ ] If the value of a field is empty, it should be presented as "--" (two dashes)

![image.png](https://images.zenhubusercontent.com/5c92ad88777e5f767e488112/fdcc547d-f077-41fd-816e-dc817576444b)

Zeplin link is here to review : https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d08fdcdf695e65dec5e3d7a.

**Comment by rosibaj** [comment]
@d8660091 Thanks for the updates - this looks great!
