### ISSUE TITLE
Program Page - Read-Only Profile Tab Static UI (for Program Admin) 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#126]
Program Administrators can see a read-only view of their program profile. This is not editable for them.

Zeplin: https://zpl.io/aND1kXe

![image](https://user-images.githubusercontent.com/15824252/59635985-7639ef00-9120-11e9-9448-bc7ecd82c064.png)

**Comment by rosibaj** [comment]
Tested https://platform-ui.qa.argo.cancercollaboratory.org/program-management 

One feedback @d8660091 @kcullion :
![image](https://user-images.githubusercontent.com/15824252/60200458-28a23e00-9814-11e9-80d2-0bea8b617d1e.png)

**Comment by kcullion** [comment]
@d8660091 

- [ ] yes the value text should be WorkSans-Regular 14px; 

- [ ] And can you try some values for the processing regions so we can get them styled too? They will come in as separate values (from checkbox component) separated by a comma.

**Comment by kcullion** [comment]
nice, thanks @d8660091 !
