### ISSUE TITLE
Remove a User Static UI and Data Hookup

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#131]
The program management UI needs to be able to remove users from programs. 

The following interactions should be completed:
- [x] When the admin clicks the garbage can icon from the users table, they receive a confirmation modal:
Zeplin: https://zpl.io/aMWZ917
![Screen Shot 2019-06-18 at 11 12 51 AM](https://user-images.githubusercontent.com/18424138/59696466-09733300-91ba-11e9-9962-a687a6ca50bf.png)

- [ ] When the admin confirms to remove this user, the modal closed and a success toast appears on the user table screen.  The toast states: ` Schrodinger Submitter has been removed from the PACA-AU program.` with the user's name and program name dynamically filled in.
![Screen Shot 2019-06-18 at 11 33 16 AM](https://user-images.githubusercontent.com/18424138/59698112-062d7680-91bd-11e9-9bff-992cf29e18d8.png)

- [ ] The program user is successfully removed from the program and is no longer visible in the users list table for that program.

**Comment by rosibaj** [comment]
@ciaranschutte For this ticket, it was scoped to static ui and data hookup.  It looks like the data hookup is not completed.  Is that correct?

**Comment by alekspejovic** [comment]
Also : 

This should say "Remove User" , and should be the smaller modal size, like the mockup.

![image.png](https://images.zenhubusercontent.com/5c92ad88777e5f767e488112/415992e3-0b38-442c-a319-2ad217498a2b)

Mockup :
![image.png](https://images.zenhubusercontent.com/5c92ad88777e5f767e488112/57711bde-2b81-4ffa-88de-f71af559a52e)

**Comment by rosibaj** [comment]
closing as will be merged after sprint
