### ISSUE TITLE
Nav bar fixes

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/argo-platform#135]
- [x] make the right and left padding smaller for this element, to match the "Submission System" element more:

![Screen Shot 2019-06-18 at 10 16 57 AM](https://user-images.githubusercontent.com/18424138/59692093-3ae80080-91b2-11e9-8237-f5f3f59e84a9.png)

- [x] make the font smaller for this element (in the case of long names) ("Hello, First Name" change to 14px and the user role change to 12px)

- [x] Change the user Initials colour to the primary dark blue: 151C3D (it's not passing accessibility checker)

- [x] Can you make sure this entire nav button is the hit target + hover state. So if the user's mouse is anywhere in this area it will trigger the a:hover and be clickable
![Screen Shot 2019-07-11 at 2 27 47 PM](https://user-images.githubusercontent.com/18424138/61075539-32b56680-a3e8-11e9-872f-769b06364808.png)

- [x] can you switch the styles for hover and active so the hover is green text + shaded background and the active is just green text and green underline: https://zpl.io/adzPEOR
![Screen Shot 2019-07-16 at 2 34 55 PM](https://user-images.githubusercontent.com/18424138/61320297-23169300-a7d7-11e9-902d-bde40fb4b23c.png)
![Screen Shot 2019-07-16 at 2 34 57 PM](https://user-images.githubusercontent.com/18424138/61320299-23169300-a7d7-11e9-9221-d8a7cb602ef2.png)

- [x] Add the "G" google icon in the top right purple button to make consistent with other call to action
![Screen Shot 2019-07-16 at 2 11 22 PM](https://user-images.githubusercontent.com/18424138/61318682-9cac8200-a7d3-11e9-953a-596e7f65d1f3.png)

- [x] Can you make the user dropdown close if the user clicks anywhere off of the dropdown - so anywhere else on the screen. 

Can make sure these states for the menu bar are working: 
- [x] logged out 
- [x] logged in with no submission access
- [x] logged in with submission access
- [x] logged in and on landing page (so user should see their user button and submission option if they have access to it)

**Comment by rosibaj** [comment]
Follow-up issue: https://github.com/icgc-argo/argo-platform/issues/352
