### ISSUE TITLE
Login/Landing page - Static UI

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#142]
Implement login/landing page:
- [x] 1 Logged out version of header/menu
- [x] 2 ARGO logo and title on left side
- [x] 3 Log in with Google button - will open the google login popup
- [x] 4 Get started callout (will eventually link to documentation and DACO registration)
- [x] 5 Right side - image grid with goal statement (see Kim for purchased image assets)

Zeplin: https://zpl.io/VQRBJqR

![Login-Page-annotated](https://user-images.githubusercontent.com/18424138/59931728-a1b82480-9413-11e9-8f17-eec3d8db6132.jpg)

**Comment by alekspejovic** [comment]
Hey @d8660091 ,

Some corrections : 
- [ ] The login with google button (#3) needs to be fixed
- [ ] The font colour for the mission statement (#5) needs to be white.

**Comment by rosibaj** [comment]
Tested and login page is work - @d8660091 Nice job :) Thank you!
