### ISSUE TITLE
Program Page: remove pagination  & search from table

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#171]
Please remove the pagination from this table.

![Screen Shot 2019-06-26 at 1 47 41 PM](https://user-images.githubusercontent.com/18424138/60202634-fe06b400-9818-11e9-9ee4-36f2da19a01c.png)

**Comment by alekspejovic** [comment]
Tested on QA. Looks good. 

![image.png](https://images.zenhubusercontent.com/5c92ad88777e5f767e488112/3a3eb997-e14f-44a0-90a2-febe5625dafa)
