### ISSUE TITLE
UI Component Library: Links

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#180]
There are two types of links.

General link (the general link style that can be anywhere within the text): 
- [ ] Default
- [ ] Hover
- [ ] Pressed
(font-size is not set within the component - it it inherited by whatever the link is within

Chevron link (a link that is more on it's own - to callout to different resources or pages_:
- [ ] Default
- [ ] Hover
- [ ] Pressed

Zeplin: https://zpl.io/adzPEOR

![Screen Shot 2019-06-27 at 1 30 05 PM](https://user-images.githubusercontent.com/18424138/60287582-3e7d3500-98e0-11e9-826f-38153254a347.png)

**Comment by rosibaj** [comment]
@hlminh2000  I don't see the chevron link in storybook?
