### ISSUE TITLE
Contact Page - Static UI

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#191]
Implement contact page (linked from footer):
- [ ] 1 Title and intro
- [ ] 2 Three resource callout areas - all links will eventually go to the documentation section
- [ ] 3 Form

Zeplin: https://zpl.io/amMpwLr
Dropdown open: https://zpl.io/boMdN8E

![Contact-dropdown](https://user-images.githubusercontent.com/18424138/60355052-975dd380-999b-11e9-89ba-90fe6b12fa6f.png)

**Comment by rosibaj** [comment]
URL for testing @kcullion https://platform-ui.qa.argo.cancercollaboratory.org/contact

**Comment by kcullion** [comment]
@d8660091 feedback: 

- [ ] intro should use subtitle2 (font-size:18px)
- [ ] add more space between line and the title/icon
- [ ] Learn more buttons: are these the right secondary button? looks like the top padding is larger than bottom
- [ ]

**Comment by d8660091** [comment]
@kcullion we don't need the recaptcha checkbox in recaptcha v3 
https://developers.google.com/recaptcha/docs/v3

**Comment by kcullion** [comment]
@d8660091 so the recaptcha3 always happens behind the scenes without interrupting user flow? That's pretty cool...
FYI @rosibaj @alekspejovic

**Comment by rosibaj** [comment]
@kcullion This looks pretty good to me for your requested changes - do you see anything else?

**Comment by kcullion** [comment]
@rosibaj we can remove the intro and "learn more" buttons - instead making the title link to the general section if you want to make more room for the form. Those won't impact the user much

**Comment by rosibaj** [comment]
@kcullion I'd rather see what everyone thinks first! those changes can be an update later if we want!

**Comment by rosibaj** [comment]
Closing as changes have been implemented and deployed!
