### ISSUE TITLE
401,404,Maintenance pages - Static UI

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#194]
Same template for the three pages: 

- [x] Implement 401 - authorization required. When a user doesn't have access to a page
Zeplin: https://zpl.io/aBKd1l0

- [x] Implement 404 - page not found.Broken links
Zeplin: https://zpl.io/VqYky05

- [x] Implement 500 - Internal Server Error

- [x] Implement Maintenance page - when ARGO needs to be taken down for a short period of time. For example, Hardeep has to lock the submission system when the dictionary is being updated
Zeplin: https://zpl.io/blMklW5

**Comment by rosibaj** [comment]
@d8660091 Can you paste the links to these pages so we can QA?

**Comment by d8660091** [comment]
/404
/401
/500
/maintenance

**Comment by d8660091** [comment]
@rosibaj Sure, they are /401, /404, /500 and /maintenance

**Comment by rosibaj** [comment]
@d8660091 A couple things:
- [ ] Please fix typo on maintenance page
![image](https://user-images.githubusercontent.com/15824252/60987328-5c4e8f00-a30f-11e9-8421-656f8cf23f32.png)

- [ ] These pages are a little large on small screens.  @hlminh2000 Do you think we should just tackle the responsiveness on these pages now?

**Comment by rosibaj** [comment]
lgtm! Thanks @d8660091 !!
