### ISSUE TITLE
Implement User Authorization in Submission area

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#202]
Depending on which type of user logs-in to the ARGO platform, we need to route them to the appropriate page/location and present the correct data/page. 

FULL SITE AUTH SPECS: https://wiki.oicr.on.ca/display/icgcargotech/Sitemap#Sitemap-PermissionsMatrixforSiteMap
Program management AUTH Specs: https://wiki.oicr.on.ca/display/icgcargotech/Program+Management+UI#ProgramManagementUI-4.4AuthorizationandNavigation

Specifically for the Program Management area:

- [ ] 1) When DCC logs in, they have access to everything.  This means they should see the DCC, RDPC and Program navigations sections.  Within the program list, they should be able to see all programs. They should be able to see and use the create Program button.
- [ ] 2)  (_OUT OF SCOPE_)When a program user logs in and they have access to *1* program, it should go to that programs dashboard. 
- [ ] 3) (_OUT OF SCOPE_) When a program user logs in and they have access to *more than 1* program, it should go to the program list listing all programs they have access to. 
- [ ] 4) When a user is role `PROGRAM ADMIN` they have access to the  `Manage Program` section (in subnav and pages)
- [ ] 6) When a user logs in and they DO NOT have access to any programs, then they should get a 401 on any submission area page they happen to access.

**Comment by joneubank** [comment]
What we need is a via that maps 1-6 logically to Ego Policies.

1. DCC user = DCC.READ or greater.
2. Program user, 1 program = exactly 1 scope of form: {short_name}-PROGRAM.{READ or greater
3. Program user, multiple programs = more than one scope of form: {short_name}-PROGRAM.READ or greater
4. Program admin = for the given program, they have {short_name}-PROGRAM.ADMIN
5. counting is hard
6. No scopes of -PROGRAM

**Comment by hlminh2000** [comment]
some notes for @rosibaj's points, just to set ticket scope, though I'm sure you've got this noted somewhere:
1) point `1)`, `"Within the program list, they should be able to see all programs"`: the control of what program to include in the programs listing will have to be handled either by program service or gateway. The gateway is already sending program service the user's ego token so it can filter its response to the `listProgram` service with the appropriate data. Alternatively, this filter can be done by the gateway as well, under the `programs` query, but it this is not a UI access control concern.
2) point `3)`, `"it should go to the program list listing all programs they have access to."`: same as above.

**Comment by rosibaj** [comment]
Program Service auth implementation can be found here:
https://github.com/icgc-argo/program-service/issues/94 .

**Comment by rosibaj** [comment]
@hlminh2000 a few fixes after testing:

Testing Results: 
[1] Logged out works correctly - no access.


[2] Logged in with a "public" email address.
 - [ ] When i have absolutely no scopes of the type `PROGRAM*`, I should receive a 401 for *any* submission area pages.  Also, the submission tab should `not` be visible on the header.
- [ ] https://platform-ui.qa.argo.cancercollaboratory.org/create-program should be a 401

[3]  Logged in as DCC Admin
* I correctly see the DCC, RDPC, and program menu. 
- [ ] I incorrectly do not have access to program pages e.x. https://platform-ui.qa.argo.cancercollaboratory.org/program/manage/ESCC-CNA user with DCC scopes should have access to any and all program pages. 

[3]  Logged in as Data Submitter
- [ ] Should not have access to `Create a Program` button
- [ ] https://platform-ui.qa.argo.cancercollaboratory.org/create-program should be a 401
- [ ] should NOT see `Manage Program` in subnav panel

[4]  Logged in as Program Admin
* See correct display on manage programs for ONLY programs i have access to 
- [ ] Should not have access to `Create a Program` button
- [ ] https://platform-ui.qa.argo.cancercollaboratory.org/create-program should be a 401
- [ ] should NOT see `Manage Program` in subnav panel for programs to which i am a member, but not an admin

[5] Program list/nav list not correctly sorted:  blocked by program service auth  (https://github.com/icgc-argo/program-service/issues/94).  To be tested later. 

Note: blocked on testing data submitter access to pages that are not manage-programs as they are not real links yet :)

**Comment by rosibaj** [comment]
Moved routing to https://github.com/icgc-argo/program-service/issues/141

**Comment by rosibaj** [comment]
Retested - still seeing this issue:
![image](https://user-images.githubusercontent.com/15824252/61325451-c15c2600-a7e2-11e9-90c5-f6b9d9c59c56.png)

**Comment by rosibaj** [comment]
Tested again - The left nav now has the correct display on the manage programs per user role, and 401 is showing on all actions for different role types. 

Further issues can be resolved in submitted bug tickets!
