### ISSUE TITLE
Column expansion issue with table component on Programs List page 

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/argo-platform#204]
When you try and expand the separator between the Administrators & Donor Status columns when the page is first refreshed, it changes the width of other columns around it instead. As an example, The first few columns (Program Name, Shortname etc) are functioning as expected.

Video of some odd behaviour: https://drive.google.com/file/d/1GPa6N_QHOsZ-6mjih8DLZbbz4fHSwDJl/view

The last column sometimes moves out of the screen and it is difficult to see the horizontal scroll bar.

**Comment by rosibaj** [comment]
tested with @alekspejovic -lgtm! Thanks @d8660091 !
