### ISSUE TITLE
Service to verify Gmail Email Address

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#255]
The authentication for ARGO will be through Google. There are 2 types of valid Google addresses: Gmail and Gsuite.  Gmail addresses end with `@gmail.com`, however GSuite emails can end with any business specific domain, i,e `@oicr.on.ca`. 

We will have several situations where we need to validation if an email address belongs to Google or GSuite. Initially, this will be used for DACO and validation on the user registration invitation. 

We need a service that can be called by other services that: 
- [ ] Can be called independently at any time
- [ ] Verifies if an email is Google or GSuite
* This can be done by checking against the DNS record. 
- [ ] Returns the error `This is not a Google or Gsuite address` in the case of failure

**Comment by d8660091** [comment]
This cannot be done. Google is pretty restrictive on user account information.
