### ISSUE TITLE
Make User Role Dynamic in top menu

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#257]
The user button in to top right side of the menu has a static "some role" user role.

We need to make this dynamic.

So for example, for a DCC Member:
![Screen Shot 2019-07-12 at 11.47.46 AM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/f60df2eb-b3a9-4035-8288-b74b893de7d5)

For a Program Member:
![Screen Shot 2019-07-12 at 11.48.03 AM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/253a53da-7592-4919-9970-f0cd73f0cfdd)

For a general user (eg - in this use case: https://github.com/icgc-argo/argo-platform/issues/252)
![Screen Shot 2019-07-12 at 11.47.35 AM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/b64eb899-263d-4f7e-8dff-252eb9b74055)

**Role detection:** use a combination of
- data from token: `isDccMember`, `isRdpcMember`, `canReadSomeProgram`
  + DCC user: `isDccMember`,
  + RDPC user: `isRdpcMember`,
  + program member: `canReadSomeProgram`
  + public user: `!isDccMember && !isRdpcMember && !canReadSomeProgram`

**Comment by rosibaj** [comment]
connect with @hlminh2000 on how to tell roll

**Comment by rosibaj** [comment]
@hlminh2000 Can you please capitalize `Member` in `Program Memberr`?
![image](https://user-images.githubusercontent.com/15824252/61505166-da640300-a9ab-11e9-9b3d-8692324d440c.png)
