### ISSUE TITLE
Can't logout from error pages

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/argo-platform#264]
**Problem**
If a user is navigated to a 401 page, they can never logout. 

Currently the `NavBar` expects the `path` and `logout` function as path. These are not being passed in for the error pages. **More importantly, new pages are not guaranteed to always receive these.**

**Solution**
`path` and `logout` are functionalities that should be globally accessible to any component. We should have an `appContext` set up at the root level `_app.js` to provide this. The `NavBar` and any other component that require this can simply pull from that context.

**Comment by alekspejovic** [comment]
Tested in QA - looks good!
