### ISSUE TITLE
Login page UI fixes

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#274]
- [x] Use an unordered list (ul) for the list here, so that they indent correctly on small screens. 
![Screen Shot 2019-07-16 at 1 30 35 PM](https://user-images.githubusercontent.com/18424138/61315976-edb97780-a7cd-11e9-99e3-a5a88449dac6.png)

- [x] the line height for this typography style seems quite squished - let's change it to line-height:42px;
![Screen Shot 2019-07-16 at 1 43 02 PM](https://user-images.githubusercontent.com/18424138/61316857-cbc0f480-a7cf-11e9-8063-aeb1cbe0e730.png)

- [ ] Can you vertically center the left side content? on large screens it's not vertically centered
![Screen Shot 2019-07-16 at 2 15 08 PM](https://user-images.githubusercontent.com/18424138/61318923-22c8c880-a7d4-11e9-9094-d0bdb89661a0.png)

Make the following changes to the hero text:
- [x] Make sure it's the brand dark blue and not black
- [x] can you make this font-weight :normal, the bold looks too bold when it's this big
- [x] can you decrease the width of the sentence so it's spans two lines when the screen is smaller (more breathing room on the left and right side of the hero text)
![Screen Shot 2019-07-17 at 1 46 21 PM](https://user-images.githubusercontent.com/18424138/61398101-4dc92000-a899-11e9-9463-096a4795dbeb.png)

**Comment by d8660091** [comment]
> Can you vertically center the left side content? on large screens it's not vertically centered

The red line is not centered

**Comment by kcullion** [comment]
yeah @d8660091 I just wanted to show you it wasn't vertically centered on any size screen :)

**Comment by kcullion** [comment]
the changes look good @d8660091. I just don't see the left side vertically centered on my large monitor. maybe we can address this when we make the page responsive.
It would be nice to see the entire page (even the footer) on a laptop size screen

**Comment by kcullion** [comment]
One other change @d8660091  - 
- [ ] please replace the ARGO logo (larger version in the content area) with the new logo in zeplin: https://zpl.io/VQRBJqR
- [ ] let's chat about the vertical center of the left side when you return
