### ISSUE TITLE
Route users on Login based on Role/permissions

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#276]
When a user logins into the submission system, they should be routed to the program list page OR a program dashboard depending on who they are/ how many programs they have access to. 

Specs: https://wiki.oicr.on.ca/display/icgcargotech/Sitemap#Sitemap-PermissionsMatrixforSiteMap

NOTE: DCC in this context is anyone with PROGRAM SERVICE scope.  PROGRAM USER is anyone with a PROGRAM-<shortname> scope.

- [ ] 2) When a program user with access to more than one program logs in OR clicks the top Submission nav, they should be navigated the program dashboard that is alphabetically first in their list of programs with access
- [ ] 3) When a program user attempts to access `submission/programs` they should get a 401 page
- [ ] 4) When a DCC logs in OR clicks the top Submission nav, they should be navigated to the program list page. The program list section of the left nav should be expanded with "All Programs" selected.

NOTE: in future, the default nav for DCC will be the DCC Dashboard, but that is not implemented yet.

**Comment by hlminh2000** [comment]
rephrasing specs:
1) DCC: `/submission/program`
2) Program user: `/submission/program/<first_accessible_program>`
3) Program user landing on `/submission/program`: 401

**Comment by rosibaj** [comment]
- logged in as dcc admin and routed to all programs so 👍 
- logged in as program admin and got https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/[shortName]/dashboard
Something went wrong with [shortname] 
- also can access program list as program admin
![image](https://user-images.githubusercontent.com/15824252/61804764-7d7ca880-ae02-11e9-80ae-e9ee3d949e24.png)

**EXPECTED BEHAVIOUR:**
- [ ] logging in as program admin should route you to the actual program page, not the bad url
- [ ] loggin in as program member I SHOULD NOT be able to access `/submission/programs`

**Comment by alekspejovic** [comment]
Tested in QA - confirmed the two points above were fixed :
![image.png](https://images.zenhubusercontent.com/5c92ad88777e5f767e488112/15620649-0c10-474c-a49e-7277e185b339)
![image.png](https://images.zenhubusercontent.com/5c92ad88777e5f767e488112/16cefc6a-130a-46ff-b980-e8757eb20f35)
