### ISSUE TITLE
Display Short Name column before  Program Name on Programs List page 

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/argo-platform#289]
default sorting is short name ascending alphabetically
![image.png](https://images.zenhubusercontent.com/5c92ad88777e5f767e488112/2bed7313-94e0-46e8-81b9-e8cf08d9346c)

**Comment by ciaranschutte** [comment]
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program

**Comment by alekspejovic** [comment]
Tested in QA , looks good!
