### ISSUE TITLE
UI Component Library: Checkboxes and Radiobuttons

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#33]
All of the states for the checkboxes and radiobuttons:

- [x]  unselected
- [x]   selected
- [x]   unselected disabled
- [x]   selected disabled
- [x]   error - discussed with @ciaranschutte 
Please display the red helper text below the checkbox/radiobutton group - but leave the form field border as is.
![Screen Shot 2019-06-17 at 1 39 11 PM](https://user-images.githubusercontent.com/18424138/59624652-50532100-9105-11e9-975a-e8f5a7abce86.png)

Zeplin: https://zpl.io/agQ1Y9N

![Screen Shot 2019-05-22 at 4 43 53 PM](https://user-images.githubusercontent.com/18424138/58207521-d324bf80-7cb0-11e9-87a9-1267b6d01fcc.png)

**Comment by kcullion** [comment]
@ciaranschutte just reviewing these components. Just a couple things...

1. The checkmark animates in as it's checked off - can it animate out the same way when it's unchecked (this may be done but can't see it working in story?) 
2. Can you vertically center the checkbox and radio button? So all the padding is equal around it
![Screen Shot 2019-06-17 at 11 40 57 AM](https://user-images.githubusercontent.com/18424138/59617773-f5b1c900-90f4-11e9-8f78-c2eb49da5f2c.png)
3. Animation: the radiobutton animation has a bit of a bounce ease.  Can we make these animation styles consistent. 
Please see: https://oicr-icgc.slack.com/files/U98QY9RUP/FKF23QLE5/UI_Animation.xml
I think we should try the types for a "strong, confident" ease like the easeInCubic, easeOutCubic

**Comment by kcullion** [comment]
@ciaranschutte just reviewing these components. Just a couple things...

1. The checkmark animates in as it's checked off - can it animate out the same way when it's unchecked (this may be done but can't see it working in story?) 
2. Can you vertically center the checkbox and radio button? So all the padding is equal around it
![Screen Shot 2019-06-17 at 11 40 57 AM](https://user-images.githubusercontent.com/18424138/59617773-f5b1c900-90f4-11e9-8f78-c2eb49da5f2c.png)
3. Animation: the radiobutton animation has a bit of a bounce ease.  Can we make these animation styles consistent. 
Please see: https://oicr-icgc.slack.com/files/U98QY9RUP/FKF23QLE5/UI_Animation.xml
I think we should try the types for a "strong, confident" ease like the easeInCubic, easeOutCubic

**Comment by ciaranschutte** [comment]
changing animation to ease-in

**Comment by kcullion** [comment]
@ciaranschutte this looks good to me! thanks :)
