### ISSUE TITLE
UI Component Library: Inputs, Selects, Search Fields

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#35]
All of the states for the inputs, selects and search fields (large and small for each):
- [x] default
- [x] focus
- [x] activated
- [x] filled out
- [x] disabled
- [x] error

![Screen Shot 2019-05-10 at 10 09 57 AM](https://user-images.githubusercontent.com/18424138/57533469-d52f6b80-730b-11e9-8cf1-58c990998ca8.png)

**Comment by hlminh2000** [comment]
The Select component still needs some more work, but the input is looking good so I'm happy with moving this forward and continue the work in later PRs
