### ISSUE TITLE
Navbar - login button not working

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#353]
- [x] The login button from the nav bar should also bring up the google login screen (landing page)

- [x] can you more the logo to the left a bit more - so it lines up more on the left with the sidebar icons. (margin-left:18px)
![Screen Shot 2019-07-30 at 9 43 23 AM](https://user-images.githubusercontent.com/18424138/62134582-beffce80-b2ae-11e9-98db-7b01afcb796c.png)

**Comment by alekspejovic** [comment]
Tested in QA - looks good!
