### ISSUE TITLE
UI Component Library: Sidebar Sub-navigation

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#37]
All of the states for the subnavigation sidebar elements:

- [ ]   Primary item - default
- [ ]   Primary item - hover
- [ ]   Primary item  - active
- [ ]   Primary item  - last 
- [ ]   Secondary item - default
- [ ]   Secondary item - hover
- [ ]   Secondary item  - active
- [ ]   Tertiary item - default
- [ ]   Tertiary item - hover
- [ ]   Tertiary item  - active
- [ ]   Tertiary item  - last
Functionality:
- [ ] Expandable accordion 
- [ ] Should see child menu options rendering 
- [ ] Scroll left nav 

Zeplin: https://zpl.io/adzPEOR
See in page: https://zpl.io/aBRPxwA

![Screen Shot 2019-05-22 at 4 37 47 PM](https://user-images.githubusercontent.com/18424138/58207072-f4d17700-7caf-11e9-9f28-8b78b49925fa.png)

![Screen Shot 2019-05-22 at 4 38 28 PM](https://user-images.githubusercontent.com/18424138/58207120-0d419180-7cb0-11e9-8fd0-e6de1df50dba.png)

**Comment by kcullion** [comment]
Looking good @hlminh2000 !

I would just say make the tertiary items a bit smaller - font-size:13px; and padding top and bottom 8px instead of 12px. 

Also, can you make the active border on the secondary and tertiary items 3px instead of 2px.

**Comment by kcullion** [comment]
also, it looks like the expandable secondary item with the button inside is taller than the other secondary item that isn't expandable. These should be the same size.
![Screen Shot 2019-06-04 at 11 56 56 AM](https://user-images.githubusercontent.com/18424138/58894369-df9d1500-86bf-11e9-8bbc-f77cf0453a2d.png)

**Comment by kcullion** [comment]
One more thing @hlminh2000  - the menu default items and icons use the "primary" dark blue colour, not black.

**Comment by hlminh2000** [comment]
thanks @kcullion for the height of the item with the button, it's just reacting to the button being there, if we didn't have the button there, it'd be the same height. You can simulate this by inspecting the button and delete the element from the browser inspector ;)

**Comment by hlminh2000** [comment]
other points are addressed in this PR: https://github.com/icgc-argo/argo-platform/pull/89/files

**Comment by kcullion** [comment]
Thanks @hlminh2000. The fixes look good. 
Just one final thing - we found that top border on the top item (DCC Dashboard) looks strange on the page.  Can you just remove it from the top item? 
So I updated this in zeplin - basically I just put a bottom border on all primary items - and thus, not having a top border anywhere

![Screen Shot 2019-06-05 at 2 02 11 PM](https://user-images.githubusercontent.com/18424138/58979266-a5a14100-879b-11e9-9e3c-ad6b140566c6.png)

**Comment by hlminh2000** [comment]
@kcullion addressed and merged to master. Should we close this now? :)

**Comment by kcullion** [comment]
Thanks @hlminh2000 I think we can close it now.  We can make new tickets with anything else when we see it on the page. 
(The only other thing maybe is to decrease the height of the secondary items - but I want to see this on the page first)
