### ISSUE TITLE
UI Component Library: Reduce height of titlebar

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#373]
- [x] Reduce the height of the titlebar to 56px 
![Screen Shot 2019-07-31 at 10 29 46 AM](https://user-images.githubusercontent.com/18424138/62220616-52ec9b80-b37e-11e9-95ed-e619247e5919.png)

**Comment by rosibaj** [comment]
lgtm thanks @ciaranschutte !
