### ISSUE TITLE
Test Data Sets

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#388]
Create three test data sets:

- PACA-AU with 10 donors, where registration should pass
- PACA-AU with 10 donors, where registration should not pass due to registration conflicts
- PACA-AU with 10 donors, where registration should not pass due to schema conflicts

**Comment by rosibaj** [comment]
@alekspejovic Do we have a link for these data sets?

**Comment by alekspejovic** [comment]
Added to the drive at the following link:

https://docs.google.com/spreadsheets/d/1I7rAW-H_o8kb2MJRMDuRSfuhXpU4Ym4bxd0eTTz4C9I/edit#gid=1639755030

Let me know if you just want the tsv files as well.
