### ISSUE TITLE
Create Program Form: Static UI

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#45]
The scope of this ticket is to create a static version of the **Create Program** form. 
- [x] Implement Program Details section with input, dropdown, multi-select and text-area components
- [x] Implement Affiliated Institutions section with multi-select component
- [ ] Implement Processing Regions section checkbox component
- [x] Implement Program Administrator with input components 
- [x] Implement Create Button

Zeplin: https://zpl.io/agQ1Y9N

![Screen Shot 2019-06-13 at 10 21 22 AM](https://user-images.githubusercontent.com/18424138/59440470-0ac0ec00-8dc5-11e9-8691-2e90199a183e.png)

**Comment by kcullion** [comment]
@d8660091 please see the new one column layout (in zeplin). This is ready for implementation
