### ISSUE TITLE
Create Program Form: Data Hookup

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#46]
The scope of this ticket is hook the Create form up to data. 

**Data Endpoint:**
https://argo-gateway.qa.cancercollaboratory.org/graphql 
Mutation: programs-service - create-program

Interactions that should be completed:
- [x] Clicking create program should navigate to the create form 
- [x] Add Website field to create form
- [x] Fields should be filled out with the following validations: 

| Field | Required | Data & Validations |
|-------------------|----------|-------------------------------------------------------------------------------------------------|
| Program Name | Y |  |
| Short Name | Y | Must be less than 9 letters; Must be all caps; Cannot contain special characters, other than a  dash (-) |
| Country | Y | This list should be selectable from the Program Service list of countries |
| Cancer Type | Y | This list should be selectable from the Program Service list of Cancer Types |
| Primary Site | Y | This list should be selectable from the Program Service list of Primary Sites |
| Commitment Level | Y | Must be greater than 0 (non-negative) |
| Membership Type | Y |  Data validation from enum (FULL or ASSOCIATE)|
| Description |  |  |
|Website||When user inputs the data, format with `http:/` if not provided|
| Institution Name |  |  |
| First Name | Y |  |
| Last Name | Y |  |
| Gmail Address | Y | Must be a valid email /gsuite address ( can lookup with DNS) |

- [ ] (not in scope) Clicking Create should save the program and navigate the user to the program list page with a success toaster! https://github.com/icgc-argo/argo-platform/issues/70
- [ ] (not in scope) the NEW muti-select input tags that the user adds, are added to the controlled list once the admin/user submits or saves the form

**Comment by joneubank** [comment]
"the NEW muti-select input tags that the user adds, are added to the controlled list once the admin/user submits or saves the form"
remove this from this ticket, this depends on the program service supplying this list and saving entries.

**Comment by joneubank** [comment]
Navigation to Programs page on success works, but no toast implemented yet.

**Comment by rosibaj** [comment]
@joneubank moved to the not-in-scope. will post ticket number when we havei t

**Comment by alekspejovic** [comment]
Some notes on the validation error messages :

![image.png](https://images.zenhubusercontent.com/5c92ad88777e5f767e488112/62e6d8d8-5159-4b85-86c5-7d127fed8dc9)

When there is an error from program-service (for example -  the last 2 letters of shortname don't correspond to the country code), nothing happens on the page to notify the user of the error or in what field it occurs. Was this in the scope of this ticket and does this depend on : https://github.com/icgc-argo/program-service/issues/131?

Otherwise looks great to me!

**Comment by joneubank** [comment]
Good catch, we added new validation rules on the backend that aren't captured in our table in this ticket. I'll confirm what the rule is with Alexis and add this in.

**Comment by joneubank** [comment]
https://github.com/icgc-argo/argo-platform/pull/248
