### ISSUE TITLE
Program List: Data Hookup

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#49]
**Endpoint:**
https://argo-gateway.qa.cancercollaboratory.org/graphql 
Query: program(...): Program

**Interactions that should be completed as part of this data hookup**
- [x] 1 - On the left nav, all programs that a user has access to should be listed. Programs should be listed alphabetically by `short-name` by default. 
- [x] 2 - The Nav search bar should filter the list below when a user types. Searchs should be on any exact matching text (whether at beginning or middle of short-name)
- [ ] 3 - All created programs should be listed in the table, alphabetically by program name
- [x] 4 - Correct # results should show
- [x] 5 - do **NOT** Implement the search here

![image](https://user-images.githubusercontent.com/15824252/59633423-71723c80-911a-11e9-952b-0557ab3c2d07.png)

**Comment by hlminh2000** [comment]
@rosibaj I split up the Selenium portion of this ticket to here: https://github.com/icgc-argo/argo-platform/issues/168

**Comment by rosibaj** [comment]
@hlminh2000 Finished testing - Everything looks good minus one thing:

![image](https://user-images.githubusercontent.com/15824252/60289860-6e7b0700-98e5-11e9-9dd0-1d2443505562.png)

Can we get this added as well?

**Comment by rosibaj** [comment]
Tested - looks great thanks @hlminh2000
