### ISSUE TITLE
UI Component Library: Tabbed Navigation

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#52]
All of the states for the tabbed bar elements:

- [x]   Tab - default
- [x]   Tab - hover
- [x]   Tab - active
- [x]   Tab - empty - to extend the bottom border to the correct width of the container
NOTE: Tabs do not need to support custom components being included. 
Zeplin: https://zpl.io/adzPEOR
Shown in a page: https://zpl.io/aBRPxwA

![Screen Shot 2019-06-06 at 11 47 04 AM](https://user-images.githubusercontent.com/18424138/59046899-d7281400-8850-11e9-9d4f-77433e2e0b47.png)

**Comment by kcullion** [comment]
@d8660091 this is looking great! Can you please

- [ ] 1. Change the default text colour to #525767 (the dark grey). Then the hover text color can be what you've specified here as the default color)

Question: can you explain what happens on the right side of the component for
"Children of empty tab goes here"
And for "Empty tab in middle"?

**Comment by d8660091** [comment]
@kcullion The empty tab is used to display the underline. It has the property of flex-grow, so it can occupy the extra spaces. It's usually put to the right as shown in the design according to Zeplin to display the underline when the tabs cannot occupy the full width of the container. It could also be put on the left or in the middle. The contents of the empty tab will be shown in the placeholder of `Children of empty tab goes here`.

**Comment by kcullion** [comment]
thanks @d8660091 
as discussed, please just remove the "empty tab in middle" story from the storybook. Then we can close this ticket!
