### ISSUE TITLE
Add Users to Program - Static UI

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#53]
The add users modal is triggered by the button on the top right of the Users page. 
- [ ] Email address must be Gmail or G Suite

- [x] The user gets a blank form and the buttons are disabled until the user starts filling out the form: https://zpl.io/a31NRyQ
![Screen Shot 2019-06-17 at 3 39 17 PM](https://user-images.githubusercontent.com/18424138/59631788-b005f800-9116-11e9-9a5a-72cc1de6cf1a.png)

- [x] When the user fills out the email field incorrectly, or fails to fill out the mandatory fields, they are thrown some errors and the "Add users" button is disabled until they fix the errors.
https://zpl.io/VkpkexL
![Screen Shot 2019-06-17 at 3 39 23 PM](https://user-images.githubusercontent.com/18424138/59631793-b4caac00-9116-11e9-96ae-2e73fc00f8ff.png)

- [x] When the user fixes the errors and can successfully add the users:
https://zpl.io/bzqJ7Bl
![Screen Shot 2019-06-17 at 3 39 27 PM](https://user-images.githubusercontent.com/18424138/59631802-b8f6c980-9116-11e9-898d-058b7b9ab6df.png)

- [x] A user cannot delete all of the user forms in the list, they should always have at least one. I.e. In the above screenshot, if the user deleted one of the user forms and is left with just one user form, the delete icon for that form is disabled.  

- [x] A user cannot keep adding blank forms. If the last form in the list is blank, the "add another" button should be disabled.

Note: the reusable modal component is outlined in: https://github.com/icgc-argo/argo-platform/issues/77

**Comment by rosibaj** [comment]
@ciaranschutte Should the Add users button launch this modal yet? It looks merged but not sure how to test it :)

**Comment by ciaranschutte** [comment]
@rosibaj not merged yet. I think it auto moved to preview because I had a stale PR I closed

**Comment by ciaranschutte** [comment]
@rosibaj do we have a separate ticket to check for gsuite we can reference here?

**Comment by rosibaj** [comment]
@ciaranschutte thats should be here: https://github.com/icgc-argo/argo-platform/issues/50

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion @alekspejovic
still need to attach it to page button.
but the UI portion (validation, activating buttons) can be viewed https://argo-ui-storybook.netlify.com/?path=/story/components-pages-submissionsystem-modals-adduser--basic

**Comment by kcullion** [comment]
Looks awesome @ciaranschutte!
Do you want to leave this ticket open for attaching it to the page button?

**Comment by ciaranschutte** [comment]
@kcullion I'm always a fan of manners :D
- "Please fill in Membership Type" is better, I agree. You're right, not filled in is not really 'invalid'.
- Gmaill/gsuite to come, yes

**Comment by kcullion** [comment]
Thanks @ciaranschutte 

In standup @rosibaj was saying to wait for a different ticket to be merged - apparently all of the error messages are coming from somewhere? So this may need to be on a separate ticket

**Comment by rosibaj** [comment]
@kcullion @ciaranschutte For Gmail yes, we agreed to integrate that error later! 
https://github.com/icgc-argo/argo-platform/issues/255
