### ISSUE TITLE
UI Component Library: Notifications - Toasts

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#70]
A toast is a lightweight, event-driven notification used for confirmations, alerts, and acknowledgments that requires minimal user interaction.

- **Position:** top right of screen, below the app navbar. 
- **Multiple toasts stack** on top of each other, most recent one at the top. When a user dismisses a toast in the stack, the older ones will move up. 
- **Time-out:** Toasts have a built-in timeout of eight seconds and may include an option to undo or dismiss  manually. 
- **Hovering over a toast prevents it from disappearing**

A toast contains:
- [ ] Icon
- [ ] Title (optional)
- [ ] Clear Description
- [ ] Actions (optional)
- [ ] X to dismiss (optional)

The background colour, border colour and icon are interchangeable.  Toasts can be 
- [ ] **Red: error** (Lets the user know something has gone wrong after a user action, or that access is denied. This message should explain the problem, avoid blame and often provide a next step or alternative.)
- [ ] **Yellow: warning** (Usually comes before an action and clearly communicates what will happen if the user proceeds, or provides alternatives. Warns the user about how to avoid errors or actions they need to take, connectivity issues, etc.)
- [ ] **Green: success** (Lets the user know they have completed an action. Creation action usually gives the option to view the created node.)
- [ ] **Blue: info** (Contains additional info that may impact the user, like significant updates to the UI. Usually no action is required. )

**Examples:** 
Info toast: 
![Screen Shot 2019-05-29 at 11 43 46 AM](https://user-images.githubusercontent.com/18424138/58571056-0dd5ad00-8207-11e9-9675-6846eac16eeb.png)

Success toast:
![Screen Shot 2019-05-29 at 11 43 51 AM](https://user-images.githubusercontent.com/18424138/58571088-18904200-8207-11e9-9e71-de2a2f244a30.png)

Zeplin: https://zpl.io/agQDLqQ
See in page context: https://zpl.io/bPxQdZM

**Related Issues:**
Banners: https://github.com/icgc-argo/argo-platform/issues/72
Inline Notifications: https://github.com/icgc-argo/argo-platform/issues/71

**Comment by hlminh2000** [comment]
for this ticket I think we can start with building just the UI component portion. Having it in the page should be a separate step as it would involve integration with the component page layout that @ciaranschutte is currently working on here https://github.com/icgc-argo/argo-platform/issues/112

**Comment by kcullion** [comment]
Thanks @hlminh2000. Can you modify the following?

- [ ] 1. Let's make "md" the default. But can you change the following with the medium sizes:
![Screen Shot 2019-06-25 at 1 47 43 PM](https://user-images.githubusercontent.com/18424138/60120878-d7c91180-974f-11e9-8f23-10cdc4ea3639.png)
