### ISSUE TITLE
UI Component Library: Tooltips

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#73]
When an icon, link, text needs more explanation - like action icons - implement a tooltip.

- [x] Tooltip default (appears on hover)
(the cursor hand is for mockup purposes)

EG:
![Screen Shot 2019-05-29 at 5 08 37 PM](https://user-images.githubusercontent.com/18424138/58591491-6a9b8c80-8234-11e9-8639-fb1302285879.png)

Zeplin: https://zpl.io/adzPEOR
See in page: https://zpl.io/blDwDnP

**Comment by kcullion** [comment]
@hlminh2000 can you change the font-size for the tooltip from 14px to 11px. Thanks!

**Comment by hlminh2000** [comment]
thanks @kcullion, addressed! :)

**Comment by kcullion** [comment]
Looks good @hlminh2000 ! I think we can close this and then look at how the positioning is working when in a page context. Thanks
