### ISSUE TITLE
UI Component Library: Percentage Cell

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#74]
A table cell can express a percentage in a more visual way.
- [x]  number/total
- [x] percentage
- [x] shaded background (blue shaded background fills to represent the percentage of the full cell width)

![Screen Shot 2019-05-30 at 10 36 55 AM](https://user-images.githubusercontent.com/18424138/58640350-de867500-82c6-11e9-9c45-0e5da95b96ed.png)

Zeplin: https://zpl.io/adzPEOR
See in page: https://zpl.io/blDwDnP

**Comment by hlminh2000** [comment]
Addressed as part of page Programs page layout. Component available to view at: https://argo-ui-storybook.netlify.com/?path=/story/uikit-percentagebar--basic

**Comment by kcullion** [comment]
@hlminh2000 
Can you make the full thing right justified - so the number and percentage.
Like ICGC: 
![Screen Shot 2019-06-17 at 1 25 16 PM](https://user-images.githubusercontent.com/18424138/59623893-6233c480-9103-11e9-8333-69b998c068c3.png)

**Comment by hlminh2000** [comment]
@kcullion addressed!

**Comment by kcullion** [comment]
thanks @hlminh2000 this looks good to me!
Have you been pushing all the storybook updates to your page? https://platform-ui.qa.cancercollaboratory.org/programs

**Comment by hlminh2000** [comment]
ah! that's the old link, Bashar's migration moved it to here: https://platform-ui.qa.argo.cancercollaboratory.org/programs
