### ISSUE TITLE
UI Component Library: Nav dropdown

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#75]
An app bar item can have multiple subsections, like the user item.
(moved out of this ticket: https://github.com/icgc-argo/argo-platform/issues/36)

- [x] Dropdown item - default
- [x] Dropdown item - hover
- [x] Dropdown item - active

My Profile and Tokens link to the same page:
Logout will log the user out of the application

![Screen Shot 2019-06-06 at 2 32 00 PM](https://user-images.githubusercontent.com/18424138/59057207-e1a1d800-8867-11e9-8651-95ff4492a78d.png)

Zeplin: https://zpl.io/adzPEOR

**Comment by rosibaj** [comment]
@d8660091 Do you mind expanding the scope of this ticket to make the buttons in the user menu functional as well as doing the component?

**Comment by d8660091** [comment]
@rosibaj No, don't mind. I'll work on that

**Comment by rosibaj** [comment]
@d8660091 
One issue: 
- [ ] The active state should not be highlighted when you are not on that page

**Comment by kcullion** [comment]
@rosibaj we also changed it to "Profile & Tokens" because they are on one page. I forgot to update this ticket.  Do we still want to do that change too? 
See zeplin: https://zpl.io/adzPEOR

**Comment by rosibaj** [comment]
@kcullion I forgot :) Yes we should get that changed!

**Comment by kcullion** [comment]
ok great! @d8660091 can you also make that change:
- [ ] There should just be one menu item for "Profile & Token"

**Comment by rosibaj** [comment]
looks great!!! thanks @d8660091!!!!
