### ISSUE TITLE
UI Component Library: Modal - Functional (large)

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#77]
A large modal box is used to provide an action that the user can optionally perform (like adding a user to a program) or to provide more detailed information (like help docs). Use a large modal for more functional processes that don't require a page within the nav menus.    

**Position:** In the middle of the screen, with the rest of the page faded.

**Size:** Should have a default size, but can be dictated by the content within. For example, for something very advanced like (like advanced filters), the modal should grow to provide more space for the content. 

**A functional modal contains:**
- [x] Title
- [x] Instructions
- [x] bottom action bar - usually a primary action button and a cancel link.
- [x] X to dismiss modal 

Example: Add users modal
![Screen Shot 2019-06-06 at 2 06 26 PM](https://user-images.githubusercontent.com/18424138/59055631-4d824180-8864-11e9-8787-8996796ff69e.png)

Zeplin: https://zpl.io/agQDLqQ
See in page: https://zpl.io/Vx0y1Ng

**Comment by hlminh2000** [comment]
@kcullion Just a note :)
I know the cancel visuall looks like a link but it isn't, so I'm making it a secondary button without border. In fact, Material UI models this as a button, so if we have this usecase often, it should be a new button variant.
https://material-ui.com/components/buttons/#text-buttons

**Comment by kcullion** [comment]
@hlminh2000  thanks for the reminder. There is a third button in zeplin that's just for text (with or without a chevron or an icon). I made a ticket for the UI component library for you here: https://github.com/icgc-argo/argo-platform/issues/169

**Comment by kcullion** [comment]
@hlminh2000 this looks great. just one small thing

- [ ] Can you put a bit more space in between the action button and cancel button. like maybe 10px
![Screen Shot 2019-06-27 at 11 08 36 AM](https://user-images.githubusercontent.com/18424138/60277627-efc5a000-98cb-11e9-9268-cb22686286fc.png)

**Comment by kcullion** [comment]
This looks good, closing the ticket!
