### ISSUE TITLE
Resend Email Invitation to User - Static UI

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#81]
- [x] When the admin clicks the email icon, they receive a confirmation modal:
Zeplin: https://zpl.io/bWNA03K
![Screen Shot 2019-05-31 at 2 17 39 PM](https://user-images.githubusercontent.com/18424138/58726121-e3265880-83ae-11e9-8927-ee1777d7f7e1.png)

- [x] When the admin confirms to resend invitation, the email is sent to the user and a success toast appears on the user table screen:
https://zpl.io/agQDLqQ
![Screen Shot 2019-05-31 at 2 20 28 PM](https://user-images.githubusercontent.com/18424138/58726252-431cff00-83af-11e9-828b-6c3274f99618.png)

**Comment by rosibaj** [comment]
QA looks good - thanks @d8660091 !
