### ISSUE TITLE
Join a Program Registration Page - Static UI

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#84]
When a user is invited to join a program by DCC admin or a Program admin, the user is sent an email (https://github.com/icgc-argo/argo-platform/issues/85 and https://github.com/icgc-argo/argo-platform/issues/86)  with a link to this page
Zeplin: https://zpl.io/bAlmz7P

- [ ] 1 Integrate form into the logged-out version of the page 
- [ ] 2 Instructions and callout with dynamic program/role info
- [ ] 3 Form 
- [ ] 4 Join Now button that will prompt the user to login with their gmail credentials (or G Suite) - using the same email address as the invitation was sent to (TBD)
- [ ] 5 logged out version of the app nav bar (login button on top right)

![image](https://user-images.githubusercontent.com/12387683/60840825-56856c00-a19e-11e9-9888-f51837de4867.png)

**Comment by hlminh2000** [comment]
page preview will be available at `https://platform-ui.qa.argo.cancercollaboratory.org/register`
the form doc: https://argo-ui-storybook.netlify.com/?path=/story/components-pages-submissionsystem-register-joinprogramform--basic

**Comment by alekspejovic** [comment]
Just a couple of corrections:
- [ ] Padding around the input text field boxes should be smaller 
- [ ] The input box for institutions is bigger height-wise than the other inputs - it should be the same size. 
- [ ] The logout button is always showing in the nav bar (don't know whether this is supposed to be addressed in another ticket)

Attached screenshot of page (on the left) beside zeplin (on the right):

![image](https://user-images.githubusercontent.com/12387683/60842147-72d6d800-a1a1-11e9-9600-851c36863e0b.png)

**Comment by hlminh2000** [comment]
@alekspejovic the navbar will be addressed separately, I think Xu might have already done this :)

**Comment by alekspejovic** [comment]
A couple of more things. (Sorry didn't say this last time, but Rosi and I just talked about it). 

For the institution, their should only be one institution per user who is joining, so the Input should be the Single select + add (should not say "Add one or more...").

@kcullion also had some comments on the sizing of the input fields and the max-width of the container. She will leave her comments below.

**Comment by kcullion** [comment]
- [ ] Please adjust the height for the Multi-select so it's the same height as the input (so it should be using the same lg version). So the height should be 36px and the placeholder text should be 14px
![Screen Shot 2019-07-11 at 4 54 50 PM](https://user-images.githubusercontent.com/18424138/61084736-9f3a6080-a3fc-11e9-956c-ed30cb1fbf16.png)

**Comment by hlminh2000** [comment]
@kcullion I originally had `600px`, but adjusted to `500px` to make it visually better resemble the design. 

I've put it back to `600px` now, but please note that it looks lightly more "spacy" than the design because of the bootstrap-style grid system which the design deviates from slightly. Matching to the design exactly at `600px` can cause some responsive issue at other screen sizes if we're not careful so I'd prefer not to try.

Let me know if we prefer `500px` and I can change it back again :)

**Comment by rosibaj** [comment]
just chiming in, but i prefer the smaller :)

**Comment by hlminh2000** [comment]
url: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/join

**Comment by kcullion** [comment]
Thanks @hlminh2000 I think 600px looks good. There's more room for the name inputs and the instructions fit nicely on one line.

**Comment by alekspejovic** [comment]
Hey @hlminh2000 , design looks good to me. Did you see the point above regarding the institution input?

**Comment by rosibaj** [comment]
@hlminh2000 @alekspejovic as discussed in standup - we will monitor this form after data hookup.  Its  possibly just the validation text that is wrong. Closing this ticket - further review in data hookup!
