### ISSUE TITLE
Email Template - Static UI

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#85]
Each system email will use a consistent template. Implement the following pieces to be used as an email template:

- [x] 1. Link if email client is not displaying email correctly: "View this email in your browser" (loads the email in the browser)
- [x] 2 Logo - links to icgc-argo.org
- [x] 3 Titlebar
- [x] 4 Content container
- [x] 5 Footer (same links as on app pages)
- [x] 6 Background-color
- [x] Find a way to serve the email template out - it WILL NOT be contained in the component library

![join-program-email](https://user-images.githubusercontent.com/18424138/59056483-5247f500-8866-11e9-9c6b-b04cf817e730.png)

Zeplin: https://zpl.io/Vqv9gLm

**Comment by d8660091** [comment]
https://github.com/icgc-argo/emails/

**Comment by d8660091** [comment]
https://argo-emails.netlify.com/

**Comment by rosibaj** [comment]
@d8660091 We need to record the architecture of where/how email templates are stored.  Can you add some details here of where the email template is/ how it can be used?

**Comment by rosibaj** [comment]
Note on implementation: 
- The email repo is used to convert a normal html page to email client friendly html page
- Then the email-client friendly html page can be copied to any other projects who need to send html email
- emails can be previewed at: https://argo-emails.netlify.com/
