### ISSUE TITLE
Invitation to Join a Program Email - Static UI

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#86]
When a user is invited to join a program (any program, any role) they are sent the following email. Implement the content with the following pieces and email tokens:

- [x] 1 Salutation with name token (dear first name last name)
- [x] 2 Program callout with icon, program name, program role, user email tokens
- [x] 3 General content including the following links: DACO approval, check out our documentation (link urls TBD)
- [x] 4 Join the Program button - links to the program registration page: https://github.com/icgc-argo/argo-platform/issues/84
- [x] 5 Closing: Sincerely - ICGC ARGO contact TBD

Zeplin: https://zpl.io/Vqv9gLm

![Screen Shot 2019-07-12 at 9 31 48 AM](https://user-images.githubusercontent.com/18424138/61131702-e457a480-a487-11e9-9753-a2dca0fa20d8.png)

**Comment by rosibaj** [comment]
@d8660091  Is there a preview link for this?

**Comment by rosibaj** [comment]
@d8660091 Is there a preview link for this?

**Comment by rosibaj** [comment]
@d8660091  i found the link.  There is one spelling error - can you please fix this?
![image](https://user-images.githubusercontent.com/15824252/61221180-eb7bee00-a6e5-11e9-89ea-b4f1a44d3e9f.png)

**Comment by kcullion** [comment]
@rosibaj this looks good - we should make a note/ticket to come back to this email to fill in the DACO and docs link

**Comment by rosibaj** [comment]
@kcullion Yes - https://github.com/icgc-argo/argo-platform/issues/271 I made this where we can track them all
