### ISSUE TITLE
UI Component Library: Change User icon to Initials

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#87]
Implement the user's first and last initials as the new user icon.

![Screen Shot 2019-06-04 at 4 16 05 PM](https://user-images.githubusercontent.com/18424138/58910657-1422c800-86e4-11e9-8620-2553fbef18c0.png)

Zeplin: https://zpl.io/adzPEOR

**Comment by kcullion** [comment]
@hlminh2000 looks good. Can you please make the right and left padding smaller for this element, to match the "Submission System" element more:
![Screen Shot 2019-06-18 at 10 16 57 AM](https://user-images.githubusercontent.com/18424138/59692093-3ae80080-91b2-11e9-8237-f5f3f59e84a9.png)

**Comment by hlminh2000** [comment]
@kcullion thanks for the review :)
I've added these points to a new ticket here: https://github.com/overture-stack/ego/issues/358

**Comment by kcullion** [comment]
Oh ok..then should this ticket be closed @hlminh2000 ?
