### ISSUE TITLE
UI Component: Table Body - Design Update

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#91]
We simplified the table body, please make the following changes:

- [x] 1 Make the header background white, not shaded
- [x] 2 The header top and bottom borders should just be 1px solid #DCDDE1;
- [x] 3 Remove the top/bottom borders from the table cells - just keep the zebra stripes
- [x] 4 Keep the bottom border on the bottom of the table 1px solid #DCDDE1;
- [x] 5 we are finding it hard to know where to adjust the column width, so please implement the light grey vertical border (1px solid #DCDDE1)

![Screen Shot 2019-06-12 at 10 29 23 AM](https://user-images.githubusercontent.com/18424138/59359788-f9aca800-8cfc-11e9-83b1-5ea3c3d0eba5.png)

Zeplin: https://zpl.io/aBRPxwA
see in page: https://zpl.io/blDwDnP

**Comment by rosibaj** [comment]
QA'd on programs page - look great thanks @hlminh2000
