### ISSUE TITLE
Gateway: Invite User

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#97]
The gateway needs to be able to send a user invitation to support the UI to invite a user

**UI Flow for this Need:**
 https://github.com/icgc-argo/roadmap/issues/17

**Inputs to  GraphQL**
- first name
- last name
- email 
- role 

**Processing Service**
Program Service (Invite User)

**Output - What happens on a successful event?**
When an invite is successfully send, then we need to indicate to the UI that it worked.  If it didn't, then

**Comment by joneubank** [comment]
https://github.com/icgc-argo/argo-platform/pull/170
