### ISSUE TITLE
Gateway: Update Program 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#98]

**Comment by joneubank** [comment]
@rosibaj should it be possible to update the number of donors (committed, submitted, genomic) through the gateway, or only do that by the submission system?

It makes sense to be able to update committed unless that number is fixed (never changeable)

**Comment by rosibaj** [comment]
- committed we can update
- submitted/genomic should be calculated by submission system.  read-only

**Comment by rosibaj** [comment]
@joneubank UNLESS the submission system uses the gateway to do those operations.
